### ISSUE TITLE
Full Screen Mode on exported MAC (non-retina)

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#87] opened 2015-06-07 09:45 UTC
Probably the problem only appear on non-retina MAC, it seems that the content is double-scaled when fullscreen is enabled.

The player is fine.

**Comment by tkhnoman** [comment] 2015-06-07 10:54
The problem seems to be it is not auto scaled.
I didn't realize because my code is like this :
		application:setWindowSize(1080, 1920)
		application:setFullScreen(true)

**Comment by ar2rsawseen** [comment] 2015-06-09 07:45
Basically it would seem autoscale only upscales but does not downscale, right?

will see what we can do about it

**Comment by ar2rsawseen** [comment] 2015-06-09 09:10
Yes autoscale works to fit the window, so the behavior makes sense

can you elaborate more on what the problem is?

**Comment by tkhnoman** [comment] 2015-06-09 09:50
The real problem is auto-scale not working when full screen is set on Exported MAC project, both upscale and downscale.
The player is fine.

(At first, i expected that it double scaled because my device is non-retina)

**Comment by ar2rsawseen** [comment] 2015-07-04 10:50
Fixed in https://github.com/gideros/gideros/commit/bd6c59185e4be3eaad20cbc1e8a06c82fbfb63b9

**Closed by ar2rsawseen** 2015-07-04 10:50 UTC
