### ISSUE TITLE
Player won't start with multiple monitors

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#152] opened 2015-09-12 21:54 UTC
If you have multiple desktops ( > 1 monitor ) and move the player to one of the other desktops then it won't start the next time you try run it.

**Comment by ar2rsawseen** [comment] 2015-11-29 14:34
Was there any specific error or anything to point us in to what could be the problem?

**Comment by rolfpancake** [comment] 2016-04-20 20:48
The issue was discussed in [this](http://giderosmobile.com/forum/discussion/comment/46952) forum thread and it can be confirmed with version 2016.04.

The workaround for this problem is as follows:

- Open a command prompt
- Type `cd %appdata%`
- Type `cd GiderosMobile`
- Edit the file GiderosPlayer.ini (located at `C:\Users\...\AppData\Roaming\GiderosMobile\GiderosPlayer.ini`)
- Change the "pos" line to `pos=@Point(0 0)`
- Restart Gideros Studio and Player

I can reproduce this issue by working with gideros on my second monitor (right side).
- I open the player and pull the window to the right edge
- I close the player window
- I try to restart the player
- The player window does not appear

In the GiderosPlayer.ini the pos line is saved like this:
`pos=@Point(2752 0)`

My monitor setup is as follows:
- 1.monitor: 1920x1080
- 2.monitor: 1680x1050

If I pull the player window to the right monitor the top left corner has the x-position `1920+1680/2 = 2760`. This seems to be the origin of the saved pos-x-argument.
If I edit the ini file with different x-values `< 1920` the player appears on my first monitor. Values above the monitor width seem to lead to an unvisible window (even nothing in the taskbar).

I hope this helps.

**Comment by hgy29** [comment] 2017-09-25 06:25
I finally got a second monitor, but I can't replicate this bug. @SinisterSoft, can you check at your side ? maybe it was fixed in QT.

**Comment by SinisterSoft** [comment] 2017-09-25 07:30
Seems fixed to me.

**Comment by hgy29** [comment] 2017-09-25 07:30
Closing then!

**Closed by hgy29** 2017-09-25 07:30 UTC
Labels: bug
