### ISSUE TITLE
gdrbridge error in OS X

### ISSUE THREAD

**Issue by Morozov-5F** [gideros/gideros#141] opened 2015-08-05 21:08 UTC
Hi everyone!
I had an issue using a `gdrbridge` tool in OS X. I got a error message: 

`./gdrbridge
dyld: Library not loaded: /usr/local/opt/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/Gideros Studio/Gideros Studio.app/Contents/Tools/./gdrbridge
  Reason: no suitable image found.  Did find:
	/usr/local/opt/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
Trace/BPT trap: 5`

I was trying to figure it out and finally i found needed frameworks in Gideros Studio.app. I copied them in directory in error message (`/usr/local/opt/qt5/lib/`) and `gdrbridge` stopped to spam this errors. 

And still it doesn't work. Now `gdrdeamon` gives me an error like this: 

`
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QtLocalPeer(0x7f83f1500fd0), parent's thread is QThread(0x7f83f1414550), current thread is QThread(0x7f83f15014c0)
QSocketNotifier: Can only be used with threads started with QThread
QObject: Cannot create children for a parent that is in a different thread.
(Parent is GiderosNetworkClient(0x7f83f1504080), parent's thread is QThread(0x7f83f1414550), current thread is QThread(0x7f83f15014c0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is GiderosNetworkClient(0x7f83f1504080), parent's thread is QThread(0x7f83f1414550), current thread is QThread(0x7f83f15014c0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Application(0x7fff5ab0e910), parent's thread is QThread(0x7f83f1414550), current thread is QThread(0x7f83f15014c0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Application(0x7fff5ab0e910), parent's thread is QThread(0x7f83f1414550), current thread is QThread(0x7f83f15014c0)
`

What's going on? Am I doing something wrong?

**Comment by hgy29** [comment] 2015-08-10 16:36
Did some tests, at least it seems to work well on Windows. So definitely some Mac specific code is failing here.

**Comment by ar2rsawseen** [comment] 2015-08-10 18:12
@Morozov-5F What Gideros version are you using? There has been fixes to this since I think 2015.07.29

**Comment by Morozov-5F** [comment] 2015-08-10 18:14
@ar2rsawseen I believe, my version is 2015.08, but where can I check it to make sure?

**Comment by Morozov-5F** [comment] 2015-08-10 18:14
@hgy29 yep, my friend is using gdrbridge on Windows, so I was surprised it was messed up

**Comment by ar2rsawseen** [comment] 2015-08-11 10:43
@Morozov-5F Either on player screen before launching an app or in Gideros studio About section

**Comment by Morozov-5F** [comment] 2015-08-11 11:27
@ar2rsawseen thanks. Yep, it's 2015.08

**Comment by Morozov-5F** [comment] 2015-08-27 16:35
@ar2rsawseen @hgy29  So, no info about this error?

**Comment by ar2rsawseen** [comment] 2015-08-27 18:08
Currently it seems to be OSX dependent, unfortunately no one of us use OSX on daily basis to try out and experiment with it

**Comment by Morozov-5F** [comment] 2015-08-27 18:39
@ar2rsawseen OK, thank you. I'll try to dig some more and see if I can find any clues about it. Maybe it'll help

**Comment by hgy29** [comment] 2015-08-29 18:08
I finally managed to compile gideros on OSX, but couldn't reproduce issue with gdrbridge/gdrdeamon. I tried launching gdrbridge from cmd line (gdrbridge getlog), no issue. Didn't try to play something yet though...

**Comment by Morozov-5F** [comment] 2015-08-29 21:14
@hgy29  Maybe gdrbridge/gdrdeamon version in release is old? Do I have to try to compile it from repo?

**Comment by hgy29** [comment] 2015-08-30 15:00
I don't think your gdrbridge/gdrdeamon can be old, but if you have time and enough energy to install every requirement needed to compile gideros from sources it and see if it works, it will help a lot. 
Whatever, I will do more tests tomorrow, if I get time...

**Comment by ar2rsawseen** [comment] 2015-09-05 13:02
I think I've finally figured it out
when you simply build gideros gdrbridge works
but when you run macdeployqt to make deployment ready binaries it mixed something and that is why it was not working in releases, while it works when we build and try it out.
Now Qt5.5 seems to fix the issue in macdeployqt so with 2015.09 release this issue should be fixed, reopen this issue if it still persists ;)

**Closed by ar2rsawseen** 2015-09-05 13:02 UTC
