### ISSUE TITLE
Impossible to download gideros.exe over many months of trying.  Other files download OK.

### ISSUE THREAD

**Issue by tonypdmtr** [gideros/gideros#459] opened 2019-01-01 16:36 UTC

**Comment by tonypdmtr** [comment] 2019-01-01 16:37
What the title says.  Is there an alternate download location?

**Comment by SinisterSoft** [comment] 2019-01-01 16:58
Hi,

Have you tried sourceforge?
https://sourceforge.net/projects/gideros/files/2018.12/


On 01/01/2019 16:37:07, tonypdmtr <notifications@github.com> wrote:
What the title says. Is there an alternate download location?

**Comment by Apollo144** [comment] 2019-01-01 18:17
@tonypdmtr Sourceforge links work better.
(with github I've experienced the same problem because of unknown isp or hosting limitations)

**Comment by totebo** [comment] 2019-01-01 20:48
I agree. When working from various AirBnb's last year, with very dodgy connections, I was able to resume the download on Sourceforge.

**Comment by tonypdmtr** [comment] 2019-01-02 18:06
Thank you all for your replies.

I have been trying from two very stable and exclusive use Internet connections (so, no AirBnb or similar). I'm trying from two different connections (home and work) from two different Internet providers and two different PCs, so I'll have to exclude provider related or PC related issues.

I don't have general download problems.  I download much larger files (several GB) from other sites without any issues.

The problem is with the gideros files.  The source archives I can download without problems but both gideros.exe and gideros.pkg (which I don't need but as a test) hang.

And I have tried different days and times of the day (or night) to avoid possible peak hour traffic issues slowing down the download to a halt.  Nothing helps.

To me, it seems to be related to the relatively large size of the files and how they are served from those platforms.

The download starts normally and after a short while (e.g., just a moment ago 101 out of 701 MB downloaded, but not always at the same point) it hangs until it eventually times out and nothing can save it.  Using WGET does not seem possible because of the way the GitHub/Sourceforge downloads are set up with connection-specific temporary links.  BTW, Sourceforge is even worse.  It usually hangs almost immediately.

This has been happening for many-many months (possibly over a year).  Before the problem started, however, I never had any problems downloading new Gideros releases on the first try.

Am I the only having these problems?

Assuming the official site publishes SHA/MD checksums for verification, could someone provide a download on some site, like filehosting.org,  etc?

**Comment by SinisterSoft** [comment] 2019-01-02 19:47
Did you try the SourceForge download?  I too have problems with large files from Github, I think it's Github's fault with slower connections.
On 02/01/2019 18:06:43, tonypdmtr <notifications@github.com> wrote:
Thank you all for your replies.
I have been trying from two very stable and exclusive use Internet connections (so, no AirBnb or similar). I'm trying from two different connections (home and work) from two different Internet providers and two different PCs, so I'll have to exclude provider related or PC related issues.
I don't have general download problems. I download much larger files (several GB) from other sites without any issues.
The problem is with the gideros files. The source archives I can download without problems but both gideros.exe and gideros.pkg (which I don't need but as a test) hang.
And I have tried different days and times of the day (or night) to avoid possible peak hour traffic issues slowing down the download to a halt. Nothing helps.
To me, it seems to be related to the relatively large size of the files and how they are served from those platforms.
The download starts normally and after a short while (e.g., just a moment ago 101 out of 701 MB downloaded, but not always at the same point) it hangs until it eventually times out and nothing can save it. Using WGET does not seem possible because of the way the GitHub/Sourceforge downloads are set up with connection-specific temporary links. BTW, Sourceforge is even worse. It usually hangs almost immediately.
This has been happening for many-many months (possibly over a year). Before the problem started, however, I never had any problems downloading new Gideros releases on the first try.
Am I the only having these problems?
Assuming the official site publishes SHA/MD checksums for verification, could someone provide a download on some site, like filehosting.org, etc?

**Comment by mokalux** [comment] 2019-09-14 01:27
no download problem so far. Should be closed?

**Comment by hgy29** [comment] 2019-09-14 04:29
I’ll close it for now, using both GH and SF should be enough and anyhow gideros can’t provide a better hosting of its releases.

**Closed by hgy29** 2019-09-14 04:29 UTC
