### ISSUE TITLE
Move to OpenSL ES on android rather than OpenAL

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#74] opened 2015-05-05 09:12 UTC
For lower latency...

See
http://giderosmobile.com/forum/discussion/1840/android-2-3-and-opensl-es/p1

**Comment by ar2rsawseen** [comment] 2016-06-19 06:54
Duplicate of https://github.com/gideros/gideros/issues/113

**Closed by ar2rsawseen** 2016-06-19 06:54 UTC
Labels: enhancement
